# Generated by Django 4.2.2 on 2023-07-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeupapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
